//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributValue
    {
        public int ID { get; set; }
        public string AttributValue1 { get; set; }
        public Nullable<int> AttributID { get; set; }
    
        public virtual Attribute Attribute { get; set; }
    }
}
